# Generated by Django 4.0.2 on 2022-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("subjects", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=300)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
