# Generated by Django 4.0.2 on 2022-03-08 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_contact_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("subjects", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=300)),
                ("date", models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.DeleteModel(
            name="contact_us",
        ),
        migrations.RemoveField(
            model_name="adress",
            name="postal_code",
        ),
        migrations.AddField(
            model_name="adress",
            name="postalcode",
            field=models.IntegerField(default=455001),
        ),
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="orderid",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpaypaymentid",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
