# Generated by Django 4.0.2 on 2022-03-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_contactus_delete_contact_us_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="shop.adress"
            ),
            preserve_default=False,
        ),
    ]
