# Generated by Django 4.0.2 on 2022-03-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="product",
            field=models.CharField(max_length=200),
        ),
    ]
