# Generated by Django 4.0.2 on 2022-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_alter_orderline_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="price",
            field=models.FloatField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderline",
            name="total",
            field=models.FloatField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
