# Generated by Django 4.0.2 on 2022-03-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_orderline_price_orderline_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="total",
            field=models.FloatField(null=True),
        ),
    ]
