# Generated by Django 4.0.3 on 2022-03-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_wishlist_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="shop.category",
            ),
        ),
    ]
